### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by ElvisDot** [lewagon/wagon-chat-api#3]
Add some flooding and XSS protection ._.
This can actually be really dangerous even tho it is just a test app.

**Comment by ssaunier** [comment]
Hello @ElvisDot,

This Rails app only serves as an API to store whatever students send to it. Its database is reset every hour. I may be wrong but how the API is vulnerable to XSS? Client code is the issue here. Do you have a gem in mind to mitigate the issue? 

For the flooding, well I really want to keep things simple and not introduce API keys. It's part of the fun of this exercise actually and with the 1 hour reset there's no real harm.

**Comment by ElvisDot** [comment]
@ssaunier i am only a beginner and just doing the bootcamp.
I have no solution to the issue. But i tried to flood the chat and spammed multiple messages and after 10 seconds the whole API was unusable until the reset. I didn't manage to get an XSS working but a teacher told me that it happened every batch.

I have no proof that the XSS is working. But imagine someone who isn't part of the bootcamp currently decides to attack the chat. And inserts some actual dangerous XSS injections in the chat. All the students would be infected.

And the spoof is just annoying. If someone curious like me trys to spam some messages the system should not go down after 10 secs and stay down until the next reset. Maybe lower the reset speed to add a rate limit for adding messages.

**Comment by ElvisDot** [comment]
Okay I looked into it again. Yes it is unstable and can be flooded easily. And yes it is possible to insert html and css but I could not get any javascript executed. So I found no security issue. Having some fun with css is fine.
